[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_AWS_REGION = "eu-north-1"
  REACT_APP_MAPBOX_ACCESS_TOKEN = "pk.eyJ1IjoieW91ci1tYXBib3gtdXNlcm5hbWUiLCJhIjoieW91ci1tYXBib3gtdG9rZW4ifQ.your-mapbox-key-part"
  # DO NOT include actual AWS credentials here for security reasons
  # Set these in Netlify's UI

# Proxy API endpoints to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Allow cross-origin image loading with expanded Mapbox permissions
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Expanded Content Security Policy to allow Mapbox resources
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https://*.amazonaws.com https://*.mapbox.com https://api.mapbox.com https://events.mapbox.com; connect-src 'self' https://*.amazonaws.com https://*.mapbox.com https://api.mapbox.com https://events.mapbox.com; script-src 'self' 'unsafe-inline' https://api.mapbox.com; style-src 'self' 'unsafe-inline' https://api.mapbox.com; worker-src blob:; child-src blob:;"

# Set up caching for images and mapbox assets
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Cache Mapbox tiles for better performance
[[headers]]
  for = "/*.pbf"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Add S3 proxy function to handle images securely and bypass CORS
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
