name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create production .env file
        run: |
          echo "REACT_APP_API_ENDPOINT=${{ secrets.PROD_API_ENDPOINT }}" > .env.production
          echo "REACT_APP_API_URL=${{ secrets.PROD_API_URL }}" >> .env.production
          echo "REACT_APP_AWS_REGION=${{ secrets.PROD_AWS_REGION }}" >> .env.production
          echo "REACT_APP_USER_POOL_ID=${{ secrets.PROD_USER_POOL_ID }}" >> .env.production
          echo "REACT_APP_USER_POOL_WEB_CLIENT_ID=${{ secrets.PROD_USER_POOL_WEB_CLIENT_ID }}" >> .env.production
          echo "REACT_APP_S3_BUCKET=${{ secrets.PROD_S3_BUCKET }}" >> .env.production
          echo "REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.PROD_MAPBOX_TOKEN }}" >> .env.production
      
      - name: Build application
        run: npm run build
        
      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_S3_BUCKET_HOSTING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
          
      - name: Invalidate CloudFront distribution
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.PROD_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
